
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 07 17:36:49 BRST 2010
//----------------------------------------------------

package com.L910;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 9;
  public static final int RES = 33;
  public static final int L_CHAVE = 25;
  public static final int R_CHAVE = 26;
  public static final int L_PAREN = 23;
  public static final int ATR = 34;
  public static final int R_PAREN = 24;
  public static final int INT = 2;
  public static final int PRINTLN = 17;
  public static final int MINUS = 30;
  public static final int REF = 13;
  public static final int VIRGULA = 21;
  public static final int AND = 43;
  public static final int NOT = 41;
  public static final int LT = 36;
  public static final int INTCONST = 7;
  public static final int OR = 42;
  public static final int INC = 18;
  public static final int DIV = 32;
  public static final int GEQ = 39;
  public static final int PLUS = 29;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 20;
  public static final int error = 1;
  public static final int IDENT = 8;
  public static final int VOID = 5;
  public static final int EQ = 35;
  public static final int READLN = 15;
  public static final int TIMES = 31;
  public static final int ELSE = 11;
  public static final int PTO_VIRGULA = 22;
  public static final int READ = 14;
  public static final int WHILE = 12;
  public static final int NE = 40;
  public static final int BOOLCONST = 6;
  public static final int LEQ = 37;
  public static final int STRING = 4;
  public static final int L_COLCH = 27;
  public static final int DEC = 19;
  public static final int R_COLCH = 28;
  public static final int GT = 38;
  public static final int PRINT = 16;
}

