
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 03 18:23:52 BRST 2010
//----------------------------------------------------

package com.L910;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int IDENT = 2;
  public static final int EOF = 0;
  public static final int INT = 3;
}

